<template>
  <v-layout
    column
    justify-center
    align-center
  >
    <v-container>
      <v-row>
        <v-col
          xs12
          sm6
          md6
        >
        </v-col>
        <v-col
          xs12
          sm6
          md6
        >
          <v-card style="width:250px">
          <v-carousel
            cycle
            height="400px"
            hide-delimiter-background
          >
            <v-carousel-item
            >
              <v-sheet
                height="100%"
              >
                <v-row
                  class="fill-height"
                  align="center"
                  justify="center"
                >
                  <v-card><v-icon color="green darken-2">fab fa-twitter</v-icon><v-icon color="green darken-2">mdi-domain</v-icon></v-card>
                </v-row>
              </v-sheet>
            </v-carousel-item>
            <v-carousel-item
            >
              <v-sheet
                height="100%"
              >
                <v-row
                  class="fill-height"
                  align="center"
                  justify="center"
                >
                  <div>cc</div>
                </v-row>
              </v-sheet>
            </v-carousel-item>
            <v-carousel-item
            >
              <v-sheet
                height="100%"
              >
                <v-row
                  class="fill-height"
                  align="center"
                  justify="center"
                >
                  <div>bb</div>
                </v-row>
              </v-sheet>
            </v-carousel-item>
          </v-carousel>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </v-layout>
</template>

<script>
export default {
}
</script>
